version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - copyloopvar
    - govet
    - gosimple
    - goconst
    - mnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    # - unused
    - unconvert
    - whitespace
    - wastedassign
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst
  settings:
    whitespace:
      multi-func: true
    lll:
      line-length: 160
    gocyclo:
      # recommend 10-20
      min-complexity: 30

formatters:
  enable:
    - gofmt
    - goimports

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - stylrcheck
  # - wsl
