// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"butterfly.orx.me/core/internal/bootstrap"
	"butterfly.orx.me/core/internal/config"
	"butterfly.orx.me/core/internal/store"
	"butterfly.orx.me/core/mod"
)

// Injectors from wire.go:

func initDeps(key mod.ConfigKey) (*bootstrap.Dependencies, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	coreConfig, err := config.ProvideCoreConfig(configConfig, key)
	if err != nil {
		return nil, nil, err
	}
	redisClients, cleanup, err := store.ProvideRedisClients(coreConfig)
	if err != nil {
		return nil, nil, err
	}
	mongoClients, cleanup2, err := store.ProvideMongoClients(coreConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sqldbClients, cleanup3, err := store.ProvideSQLDBClients(coreConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	s3Store, err := store.ProvideS3Store(coreConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dependencies := &bootstrap.Dependencies{
		Config:     configConfig,
		CoreConfig: coreConfig,
		Redis:      redisClients,
		Mongo:      mongoClients,
		SQLDB:      sqldbClients,
		S3:         s3Store,
	}
	return dependencies, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
