# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feat*" ]

jobs:

  test:
    runs-on: ubuntu-latest
    container: golang
    services:
      # Label used to access the service container
      consul:
        # Docker Hub image
        image: hashicorp/consul:1.18
    env:
      BUTTERFLY_CONFIG_CONSUL_ADDRESS: "consul:8500"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
